# Dockerfile for the backend
# base image is Eclipse Temurin JDK 17
FROM eclipse-temurin:17-jdk-alpine

# set the working directory
WORKDIR /app

# copy jar file to the container
COPY target/aha-0.0.1-SNAPSHOT.jar /app/aha.jar

# expose the port
EXPOSE 8080

# run the jar file
CMD ["java", "-jar", "aha.jar"]