spring.application.name=aha
server.port=${SERVER_PORT:8080}

#Redis Configuration
spring.cache.type=redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

#CORS / WebSocket Allowed Origins
app.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}

#Cookie Configuration
app.cookie.secure=${COOKIE_SECURE:false}

#Swagger Configuration
springdoc.swagger-ui.path=${SPRINGDOC_SWAGGER_UI_PATH:/docs}
